name: release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - name: 🧪 Test
        run: |
          npm install
          npm test
      - name: 🎉 Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
